apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: sge
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: cesar02dd/mysql:latest
        ports: 
          - containerPort: 3306
        volumeMounts:
          - name: storage
            mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "yes"
          - name: MYSQL_DATABASE
            value: "sd"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mysql-pvc
